In [12]:
import pandas as pd
import numpy as np
# 读取数据
df = pd.read_csv(r'D:\My_First_Project\src\data\user_data.csv')

# 查看前五行
df.head()

,Churned,Membership_Years,Signup_Quarter,Login_Frequency,Session_Duration_Avg,Total_Purchases,Days_Since_Last_purchase,Average_Order_Value,Cart_Abandonment_Rate,Customer_Service_calls,Returns_Rate,Discount_Usage_Rate,Product_Reviews_Written
0,0,2.9,Q1,14.0,27.4,9.0,34.0,94.72,50.6,9.0,2.0,46.40,4.0
1,0,1.6,Q4,15.0,42.7,19.5,71.0,82.45,37.7,7.0,9.2,57.96,3.0
2,0,2.9,Q4,10.0,24.8,9.1,11.0,165.52,70.9,4.0,11.5,12.24,1.0
3,0,2.6,Q1,10.0,38.4,15.0,47.0,147.33,41.7,2.0,5.4,44.10,5.0
4,0,3.1,Q4,29.0,51.4,32.5,73.0,141.30,19.1,1.0,5.5,25.20,11.0

In [13]:
# 数据集的行列数
print(f"数据集形状：{df.shape}")

# 查看数据类型、缺失值
df.info()

数据集形状：(50000, 13)
<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Churned                   50000 non-null  int64
 1   Membership_Years          50000 non-null  float64
 2   Signup_Quarter            50000 non-null  str
 3   Login_Frequency           50000 non-null  float64
 4   Session_Duration_Avg      46601 non-null  float64
 5   Total_Purchases           50000 non-null  float64
 6   Days_Since_Last_purchase  47000 non-null  float64
 7   Average_Order_Value       50000 non-null  float64
 8   Cart_Abandonment_Rate     50000 non-null  float64
 9   Customer_Service_calls    49832 non-null  float64
 10  Returns_Rate              45509 non-null  float64
 11  Discount_Usage_Rate       46500 non-null  float64
 12  Product_Reviews_Written   46500 non-null  float64
dtypes: float64(11), int64(1), str(1)
memory usage: 5.0 MB

In [14]:
# 数值字段统计
df.describe()

,Churned,Membership_Years,Login_Frequency,Session_Duration_Avg,Total_Purchases,Days_Since_Last_purchase,Average_Order_Value,Cart_Abandonment_Rate,Customer_Service_calls,Returns_Rate,Discount_Usage_Rate,Product_Reviews_Written
count,50000.000000,50000.000000,50000.000000,46601.000000,50000.000000,47000.000000,50000.000000,50000.000000,49832.000000,45509.000000,46500.000000,46500.000000
mean,0.289000,2.984009,11.624660,27.660754,13.111576,29.792872,123.117330,57.079973,5.681831,6.680913,41.997485,2.853312
std,0.453302,2.059105,7.810657,10.871013,7.017312,29.695062,175.569714,16.282723,2.676052,6.143027,21.373642,2.328948
min,0.000000,0.100000,0.000000,1.000000,-13.000000,0.000000,26.380000,0.000000,0.000000,0.000000,0.240000,0.000000
25%,0.000000,1.400000,6.000000,19.700000,8.000000,9.000000,87.050000,46.400000,4.000000,2.900000,25.300000,1.000000
50%,0.000000,2.500000,11.000000,26.800000,12.000000,21.000000,112.970000,58.100000,5.000000,5.400000,40.200000,2.000000
75%,1.000000,4.000000,17.000000,34.700000,17.000000,41.000000,144.440000,68.700000,7.000000,9.100000,57.000000,4.000000
max,1.000000,10.000000,46.000000,75.600000,128.700000,287.000000,9666.379178,143.743350,21.000000,99.615734,116.640000,21.000000

In [15]:
# 查看缺失值占比（%)
missing_pct = (df.isnull().sum() / len(df)) * 100
print(missing_pct)

Churned                     0.000
Membership_Years            0.000
Signup_Quarter              0.000
Login_Frequency             0.000
Session_Duration_Avg        6.798
Total_Purchases             0.000
Days_Since_Last_purchase    6.000
Average_Order_Value         0.000
Cart_Abandonment_Rate       0.000
Customer_Service_calls      0.336
Returns_Rate                8.982
Discount_Usage_Rate         7.000
Product_Reviews_Written     7.000
dtype: float64

In [16]:
#处理缺失值
max_day = df['Days_Since_Last_purchase'].max()
df.fillna({
    'Session_Duration_Avg': 0,
    'Days_Since_Last_purchase': max_day+1,
    'Customer_Service_calls': 0,
    'Returns_Rate': 0,
    'Discount_Usage_Rate': 0,
    'Product_Reviews_Written': 0
}, inplace=True)

,Churned,Membership_Years,Signup_Quarter,Login_Frequency,Session_Duration_Avg,Total_Purchases,Days_Since_Last_purchase,Average_Order_Value,Cart_Abandonment_Rate,Customer_Service_calls,Returns_Rate,Discount_Usage_Rate,Product_Reviews_Written
0,0,2.9,Q1,14.0,27.4,9.0,34.0,94.72,50.6,9.0,2.0,46.40,4.0
1,0,1.6,Q4,15.0,42.7,19.5,71.0,82.45,37.7,7.0,9.2,57.96,3.0
2,0,2.9,Q4,10.0,24.8,9.1,11.0,165.52,70.9,4.0,11.5,12.24,1.0
3,0,2.6,Q1,10.0,38.4,15.0,47.0,147.33,41.7,2.0,5.4,44.10,5.0
4,0,3.1,Q4,29.0,51.4,32.5,73.0,141.30,19.1,1.0,5.5,25.20,11.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,0,10.0,Q2,10.0,35.8,13.0,18.0,156.76,51.2,5.0,0.0,62.70,1.0
49996,0,1.4,Q3,21.0,32.4,15.0,48.0,103.31,32.5,5.0,0.0,66.30,3.0
49997,0,2.8,Q1,19.0,40.3,12.0,7.0,139.44,50.6,4.0,10.7,0.00,6.0
49998,0,2.9,Q2,17.0,29.9,12.0,72.0,111.58,60.8,5.0,2.5,74.20,2.0
49999,0,2.2,Q3,2.0,18.2,9.0,37.0,132.67,46.0,7.0,3.5,2.90,0.0

In [17]:
# 处理重复行
duplicates = df.duplicated().sum()
print(f"重复行数: {duplicates}")
if duplicates > 0:
    df = df.drop_duplicates()

重复行数: 0

In [18]:
# Total_Purchases总购买次数存在负数,将负数改为0
df.loc[df['Total_Purchases']<0,'Total_Purchases'] = 0

# Cart_Abandonment_Rate弃购率存在超过100，截断到[0,100]
df['Cart_Abandonment_Rate'] = df['Cart_Abandonment_Rate'].clip(0,100)

# Discount_Usage_Rate折扣使用率存在超过100,截断到[0,100]
df['Discount_Usage_Rate'] = df['Discount_Usage_Rate'].clip(0, 100)

In [19]:
cols_to_convert = df.select_dtypes(include=[np.number]).columns
for col in cols_to_convert:
    if col in df.columns and df[col].dtype == 'object':
        df[col] = pd.to_numeric(df[col], errors='coerce')
print(df.dtypes)

Churned                       int64
Membership_Years            float64
Signup_Quarter                  str
Login_Frequency             float64
Session_Duration_Avg        float64
Total_Purchases             float64
Days_Since_Last_purchase    float64
Average_Order_Value         float64
Cart_Abandonment_Rate       float64
Customer_Service_calls      float64
Returns_Rate                float64
Discount_Usage_Rate         float64
Product_Reviews_Written     float64
dtype: object

In [20]:
# 整体流失率
churn_rate = df['Churned'].mean()
print(f"整体流失率: {churn_rate:.2%}")

整体流失率: 28.90%

In [21]:
df.to_csv(r'D:\My_First_Project\src\data\cleaned_user_data.csv', index=False)
print("清洗后的数据已保存为 cleaned_user_data.csv")

清洗后的数据已保存为 cleaned_user_data.csv